# Generated by Django 4.2.18 on 2025-02-02 20:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(choices=[(datetime.time(8, 30), '8:30'), (datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00')])),
                ('dog_name', models.CharField(max_length=150, verbose_name="dog's name")),
                ('dog_breed', models.CharField(max_length=150, verbose_name="dog's breed")),
                ('dog_size', models.IntegerField(choices=[(0, 'Large (>25kg)'), (1, 'Medium (10-25kg)'), (2, 'Small (<10kg)')], default=0, verbose_name="dog's size")),
                ('additional_notes', models.TextField(blank=True)),
                ('canceled', models.BooleanField(default=False, verbose_name='canceled?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.service')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
