# Generated by Django 4.2.18 on 2025-02-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', 'time']},
        ),
    ]
