# Generated by Django 4.2.18 on 2025-01-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquirer_name', models.CharField(max_length=200, verbose_name='name')),
                ('enquirer_email', models.EmailField(max_length=254, verbose_name='email')),
                ('enquirer_phone', models.CharField(max_length=20, verbose_name='phone')),
                ('content', models.TextField(verbose_name='enquiry')),
                ('read', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_on'],
            },
        ),
    ]
